wso2-extensions/identity-conditional-auth-functions

.gitignore
pom.xml

pom.xml and  .gitignore files added.

Initialization of the repository with pom.xml 

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasRoleFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasRoleFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceHolder.java
pom.xml

Resolves https://github.com/wso2/product-is/issues/3159
Partial Fix for https://github.com/wso2/product-is/issues/3173
- Move hasRole Function from framework repo
- Improve hasRole Function to use a user from any given step
Following is a some sample usage of this new method.
`var user = context.steps[1].subject;`
`var isAdmin = hasRole(user, 'admin');`
`Log.info('--------------- Has Admin ' + isAdmin);`

Add HasRole Function with the Improvements.

---

.gitignore
components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/SendEmailFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/SendEmailFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/internal/NotificationFunctionServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/internal/NotificationFunctionServiceHolder.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
pom.xml

Resolves https://github.com/wso2/product-is/issues/3179
> Add native function to send emails.
`var user = context.steps[1].subject;
var firstName = user.localClaims['http://wso2.org/claims/givenname'];
sendEmail(user, 'myTemplate', {'firstName':firstName});
`

Add native function to send emails

---

components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/CallSiddhiFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/CallSiddhiFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/internal/SiddhiFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/internal/SiddhiFunctionsServiceHolder.java
pom.xml

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Add function to call siddhi for adaptive authentication decision

---

components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/CallHTTPFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/CallHTTPFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/CallSiddhiFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/PublishSiddhiFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/PublishSiddhiFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.siddhi/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/siddhi/internal/SiddhiFunctionsServiceComponent.java

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Add function to publish events to siddhi

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallSiddhiFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallSiddhiFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CallHTTPFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CallHTTPFunctionImpl.java

- Remove unnecessary consumers.
- Refactor variable names.

Refactor long wait node functions

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallAnalyticsFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallAnalyticsFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/PublishToAnalyticsFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/PublishToAnalyticsFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/internal/SiddhiFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/internal/HTTPFunctionsServiceComponent.java

- Fix import package issues.
- Handle the scenarios of not having any cookie.
- Introduce http get method (httpGet).
- Change callHTTP function to httpPost.

Refactor adaptive auth functions

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallAnalyticsFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/PublishToAnalyticsFunctionImpl.java

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Modify data publish methods to analytics

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java

hasAnyOfTheRoles function is similar to hasRole function. Instead of single role, it accepts a list of roles where it will return true if user has any of those roles.

Add hasAnyOfTheRoles function

---

components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml

Fix http functions component activation failure

Fix bundle activation failure

---

features/org.wso2.carbon.identity.conditional.auth.functions.server.feature/pom.xml
pom.xml

> Add feature for to pack the jars.

Add feature for to pack the jars

---

components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/notification/sendEmail-test-sp.xml
components/org.wso2.carbon.identity.conditional.auth.functions.test.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/test/utils/sequence/JsSequenceHandlerRunner.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesFunctionImplTest.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/user/hasAnyOfTheRoles-test-sp.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/user/hasRole-test-sp.xml

Add tests for hasAnyOfTheRoles function

Add tests for hasAnyOfTheRoles function

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/PublishToAnalyticsFunctionImpl.java

To fix the URL construction issue in PublishToAnalyticsFunctionImpl where "/" is not appended after port
Resolves https://github.com/wso2/product-is/issues/3730

URL construction issue in PublishToAnalyticsFunctionImpl fixed

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetAssociatedLocalUserFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetAssociatedLocalUserFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
pom.xml

Fixes https://github.com/wso2/product-is/issues/3984

Introduce new function to get associated local user of a federated user

---

components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/SendEmailFunctionImpl.java
pom.xml

> Fix wso2/product-is#3751
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

New-Device-Based template gives an error when the user does not have a email address Fixed

---

components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/GetUserWithClaimValues.java
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/UserStoreFunctions.java
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/internal/UserStoreFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/internal/UserStoreFunctionsServiceHolder.java
features/org.wso2.carbon.identity.conditional.auth.functions.server.feature/pom.xml
pom.xml

```JsAuthenticatedUser getUniqueUserWithClaimValues(Map<String, String> claimMap, Object... parameters)```
The claim map will consist of the claim and value. The function will get the 1st key from the map and get all users with the claim and add to list. Then remove the users from that list not having the other claims. So the order of the map will decide the performance of this function. The first claim in this must have low number of users.
Fix wso2/product-is#4884
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the …

Add user store adaptive function

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml

Related https://github.com/wso2/product-is/issues/6012

Fix duplicate package import in user component

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.common/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.jwt.decode/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.session/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.test.utils/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/IsAnyOfTheRolesAssignedToUserFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/IsAnyOfTheRolesAssignedToUserFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
features/org.wso2.carbon.identity.conditional.auth.functions.server.feature/pom.xml
pom.xml

Resolves https://github.com/wso2/product-is/issues/6729

Implement IsAnyOfTheRolesAssignedToUser function

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.common/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.jwt.decode/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.session/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.test.utils/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
features/org.wso2.carbon.identity.conditional.auth.functions.server.feature/pom.xml
pom.xml

Upgrade kernel version and release minor version

Upgrade kernel version and release minor version

---

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunctionImpl.java

Resolves: https://github.com/wso2/product-is/issues/8386
Setting the outcome correctly for invalid URLs

Setting outcome types for exceptions in HttpGet and HttpPost methods

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/AnalyticsEngineConfigImpl.java

- Change connector names and categories according to wso2/identity-apps#1007
- Modify connector property names and descriptions for better UX.

Modify connector field names and descriptions and fix minor issues.

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/AnalyticsEngineConfigImpl.java

Closes https://github.com/wso2/product-is/issues/7783

Correct the Identity Server Analytics engine default value

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/IsMemberOfAnyOfGroupsFunctionImplTest.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/user/isMemberOfAnyOfGroups-test-sp.xml

Adding unit tests for user group based adaptive authentication.

Add unit tests for groups adaptive auth script

---

components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/UserStoreFunctions.java

Fixes https://github.com/wso2/product-is/issues/11569

Fix the issue of returning username with userstore domain

---

components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/UserStoreFunctions.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
pom.xml

Fixes https://github.com/wso2/product-is/issues/11777
Adding JSAuthencationContext as the second param to resolve NPE.
We need xml-apis dependency because of build failure
Ref: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project org.wso2.carbon.identity.conditional.auth.functions.user: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
```

Improve getUniqueUserWithClaimValues Function

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetUserSessionsFunctionImpl.java

Resolves: wso2/product-is#11689
Resolving user ID from the username (using newly implemented the uniqueId functions).
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. …

Resolve userId from username

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetAssociatedLocalUserFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/SetAccountAssociationToLocalUserImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/Utils.java

> $subject
> Improvement related to fix https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/68

Fix subject identifier not resolving issue in GetAssociatedLocalUserFunction

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/pom.xml
features/org.wso2.carbon.identity.conditional.auth.functions.server.feature/pom.xml

> Part of [identity-conditional-auth-functions#74](https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/74)

Update feature pom with callChoreo

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/SetAccountAssociationToLocalUser.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/SetAccountAssociationToLocalUserImpl.java

Fixes https://github.com/wso2/product-is/issues/12055
This method change doesn't affect the existing usages, because we are returning a value now. Previously it was a void method. There are no parameter changes.

Return federated user association status

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetAssociatedLocalUserFunctionImpl.java

Fix issue in GetAssociatedLocalUserFunction imports

---

components/org.wso2.carbon.identity.conditional.auth.functions.test.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/test/utils/sequence/JsSequenceHandlerRunner.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
pom.xml

Fix unit test failures

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/internal/ChoreoFunctionServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/internal/ChoreoFunctionServiceHolder.java
pom.xml

**Purpose**
>Adaptive script gives the API key alias and the key is resolving  inside the callChoreo function.

Improve callChoreo by intergrating SecretResolveManager

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/ClientManager.java
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/internal/ChoreoFunctionServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/internal/ChoreoFunctionServiceHolder.java
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/choreo/risk-test-sp.xml

Refactor callChoreo function.

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/SetAccountAssociationToLocalUserImpl.java

Improve validations of user association function

Improve validations of user association function

---

components/org.wso2.carbon.identity.conditional.auth.functions.session/pom.xml
pom.xml

This PR will update httpcore, httpclient and httpasyncclient versions.

Updating httpcomponent versions

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.common/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.jwt.decode/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.session/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.test.utils/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
features/org.wso2.carbon.identity.conditional.auth.functions.server.feature/pom.xml
pom.xml

change version to 1.1.24-SNAPSHOT

---

components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/UserStoreFunctions.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetUserSessionsFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/TerminateUserSessionImpl.java
pom.xml

Add Update commits to 1.1.x

---

pom.xml

Mistakenly used the version range for dependency version. Fixed it through this PR.

Fix the issue with version range

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesFunctionImpl.java

> $subject
> https://github.com/wso2/product-is/issues/13204
> https://github.com/wso2-support/identity-conditional-auth-functions/pull/41

Fix error in resolving domain from fIDP encoded username

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java

This PR resolves https://github.com/wso2-enterprise/asgardeo-product/issues/9450.
this PR should resolve the issue mentioned in https://github.com/wso2-enterprise/asgardeo-product/issues/9450
Only a part of exceptions are caught in the original code. This PR adds a catch block to catch other possible exceptions.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus …

Catch Other Exceptions in completed Method

---

components/org.wso2.carbon.identity.conditional.auth.functions.common/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/common/utils/ConfigProvider.java

Change warn log to debug log

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.elk/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.jwt.decode/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.session/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.test.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/test/utils/sequence/JsSequenceHandlerAbstractTest.java
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetAuthenticatedApplicationsFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetAuthenticatedAppsFuncImp.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
pom.xml

> Purpose of this pull request is to introduce a conditional authentication function (`getAuthenticatedApplications`) which will retrieve the list of names of authenticated applications of a given session.
- [https://github.com/wso2-enterprise/asgardeo-product/issues/10795](https://github.com/wso2-enterprise/asgardeo-product/issues/10795)

Introducing GetAuthenticatedApplications function

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java

$subject in order to resolve comments on the merged PR https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/99/files 
$subject
> Link to the PR for changes to the training content in …

Address PR Comments

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/ClientManager.java

* Improve client connection pool creation for call choreo function.

Improve client connection pool creation

---

components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/AbstractElasticHelper.java
components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/CallElasticFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/HttpClientManager.java
components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/internal/ElasticFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/internal/ElasticFunctionsServiceHolder.java

Addressed the comments on PRs after code review.
- https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/98

Address comments after code review

---

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImplTest.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/SimpleCryptoProviderTest.java

> $subject
https://github.com/wso2/product-is/issues/15134

Refactor a test file name for Cookie Function test

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.elk/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
pom.xml

The identity components are bumped to major versions created for IPK.

Update Dependencies to IPK versions

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java

With this PR, the `SecretManagementClientException` thrown when user does not define `ConsumerKey` or `ConsumerSecret` for the Choreo based API, will be logged as debug log.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …

Log SecretManagementClientException as debug log

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/ClientManager.java
components/org.wso2.carbon.identity.conditional.auth.functions.common/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/common/utils/Constants.java

callChoreo timeouts timeout configurations

callChoreo timeout configurations

---

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.choreo/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.common/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/internal/NotificationFunctionServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/internal/NotificationFunctionServiceHolder.java
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/internal/UserStoreFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/internal/UserStoreFunctionsServiceHolder.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/Utils.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceHolder.java

Remove carbon registry dependency

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/Utils.java

Fix java.lang.NoClassDefFoundError: org/wso2/carbon/user/core/tenant/TenantManager

Fix NoClassDefFoundError

---

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java

Added comment to improve readability

---

features/org.wso2.carbon.identity.conditional.auth.functions.server.feature/pom.xml
pom.xml

-  $Subject 
- Related to https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/148

Adding `conditional.auth.functions.utils` component to `conditional.auth.functions.server.feature`

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/AssignUserRolesV2Function.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/AssignUserRolesV2FunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesV2Function.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesV2FunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/RemoveUserRolesV2Function.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/RemoveUserRolesV2FunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceHolder.java

- Fix https://github.com/wso2/product-is/issues/17543
> Link(s) to product documentation that addresses the changes of this PR. …

Add new conditional functions based on Role V2

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesV2FunctionImpl.java

> Resolves https://github.com/wso2/product-is/issues/18670
> Link to the PR for changes to the training content in …

Fix issue where role associated to user groups not considered

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/AssignUserRolesV2FunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesV2FunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/RemoveUserRolesV2FunctionImpl.java

> $subject
- https://github.com/wso2/product-is/issues/18832

 Ignore the Internal domain prefix in `hasAnyOfTheRolesV2` and `assignUserRolesV2` methods

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml

- $Subject
- https://github.com/wso2/product-is/issues/18866

Add Missing Framework `openjdk.nashorn` Import Package into Conditional Auth User Functions Component 

---

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/internal/HTTPFunctionsServiceComponent.java

Fix setCookie and getCookieValue adaptive auth function issue

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/model/JsWrapperFactoryProvider.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/model/graaljs/JsGraalUserSession.java

- Fix the logic to resolve the correct JsWrapperFactoryProvider
- Return proper graal proxy objects from Graal User Session

Fix issues in converting to proxy objects for user sessions

---

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/AbstractHTTPFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunction.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/internal/HTTPFunctionsServiceComponent.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/internal/HTTPFunctionsServiceHolder.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunctionImplTest.java
components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunctionImplTest.java

This PR addresses comments in https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/140.

Fix license headers

---

components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/SendEmailFunctionImpl.java

Sanitizing error message in send email adaptive auth function.

Sanitizing error message in send email adaptive auth function

---

components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml

Related Issue: https://github.com/wso2-enterprise/asgardeo-product/issues/24918
Related PR: https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/185

Add missing masking related dependencies

---

.github/workflows/pr-builder.yml
codecov.yml
pom.xml

$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Intergrate codecov to calculate the unit test coverage 

---

components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/ElasticAnalyticsEngineConfigImpl.java

Fixes https://github.com/wso2/product-is/issues/22674
UI with the fix

Fix ELK connection URL

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImpl.java

- $subject
- Clear the password from the memory after using it.
- clearPassword method will clear the password from the memory after password is updated.

Clear the password from the memory after updating the password

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.conditional.auth.functions.utils/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/utils/ResolveMultiAttributeLoginIdentifierFunctionImpl.java

Add review suggestions

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImpl.java

> $subject
- https://github.com/wso2/product-is/issues/24228
Need to update the documentation about this support.

Clear skip password thread local after skipping password validation

---

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImpl.java
components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImplTest.java

Add tenant validation in update password flow
