components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/GetCookieFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/SetCookieFunction.java
> Make properties as optional parameter
`setCookie(context.response, "name", "test") ` and` getCookieValue(context.request,"name")` will work no need to put ` {} `as last parameter.
=> Make properties as optional parameter

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallAnalyticsFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/ClientManager.java, components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/PublishToAnalyticsFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/internal/AnalyticsFunctionsServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/listener/AnalyticsAxis2ConfigurationContextObserver.java, pom.xml
- Use httpasyncclient to invoke analytics engine.
- Create tenant-wise http client and clean the client properly when the tenant is unloaded.
=> Use httpasyncclient to invoke analytics engine

components/org.wso2.carbon.identity.conditional.auth.functions.test.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/test/utils/sequence/JsSequenceHandlerAbstractTest.java
=> Fix tests failure when the carbon-identity-framework version is upgraded

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/SetAccountAssociationToLocalUserImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceHolder.java
Fixes https://github.com/wso2/product-is/issues/11586
When adding federated user association,
Use IDP's user id claim URI as the external subject when claim mappings are defined for IDP. Otherwise use the federated user's subject identitfier.
=> Use the value mapped to IDP's user id claim uri as external subject,  when claim mappings are defined

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/GetUserSessionsFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/TerminateUserSessionImpl.java
> Fix https://github.com/wso2/product-is/issues/12812
> The user Id of the user was being retrirved from the IDN_AUTH_USER table, and as local user records are not inserted to the table, the user Id was returning a null and thus session termination was a failure. 
> To retrieve user Id from the userstore based on given parameters.
> Updated method of retrieving user Id at session termination function.
=> Update user Id retrieval approach in terminateUserSession function

components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/internal/ElasticFunctionsServiceComponent.java
Server configuration service binding is added to the `ElasticFunctionsServiceComponent`
Resolves https://github.com/wso2/product-is/issues/13995
=> Fix error log observed related to ELK when the pack starts

components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/CryptoProviderTest.java, pom.xml
> $subject
> Remove the Base64 decode step , that used to decode a string that is not encode in `setCookie` method
> Remove the extra encode step from the `getCookieValue` method
> Implement new unit tests for test the functions with special characters with encryption
> https://github.com/wso2/product-is/issues/15134
=> Fix Signing or encrypting of tokens gives unexpected result issue

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImpl.java
-  $subject
- This fix is done for keep backward compatible of encrypt and decrypt cookie values after migration.
- Can use below configuration to deployment.toml file and keep the cookie values valid after the migration also.
```
[system.parameter]
enableAdaptiveScriptCookieLegacyMode=true
```
https://github.com/wso2/product-is/issues/15134
=> Fix backward compatibility of encrypt and decrypt cookies

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesFunctionImpl.java
Fixes https://github.com/wso2/product-is/issues/15350
`user.getContext().getSubject()` returns null when the the user is SSO'd in. Hence causing the NPE in [#15350](https://github.com/wso2/product-is/issues/15350) when `isFederatedUser()` is called.
Here, we are using a null-safe method for checking if the authenticated user is federated.
=> Use a null-safe method for checking if the user is federated

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/Utils.java
> When doing the federated association, it checks whether there is an idp claim mapped to the username local claim. If not it picks the idp subject identifier as the external User ID. As a result, there is no proper association created and it prompts for the account linking every time. Therefore, we try to get it directly from the user ID claim uri configured for the IDP.
=> Fix issues in resolving userIdClaimUri

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java
* Allow calling the asgardeo token endpoints to retrieve tokens
*  provide the capability to work with all the success HTTP responses (2xx)
With this change, the tokenEndpoint can be provided through the `connectionMetadata` as follows,
```
var connectionMetadata = {
"url": "xxxxxxxxxxxxxxxxxx",
"consumerKey": "xxxxxxxxxxxxxx",
"consumerSecret": "xxxxxxxxxxxxxxxxx",
"asgardeoTokenEndpoint": "https://api.asgardeo.io/t/<tenant>/oauth2/token"
};
```
=> Allow to call the Asgardeo token endpoint

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/IsMemberOfAnyOfGroupsFunctionImpl.java
-  $subject
-  Previosuly, federated IDP's groups are mapped to the application role claim URI
-  Now, it is changed and federated IDP's groups are mapped to the local groups claim URI.
https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/132
=> Change the local groups claim uri of the IsMemberOfAnyGroups Adaptive Fucntion

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java
> [P1] [INC0019190] Intermittent login failures caused by callChoreo function issues
> To fix the connection timeout of the Choreo token call.
> * https://github.com/wso2-enterprise/asgardeo-product/issues/19194
=> Retry method incorporated for token time-out

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.common/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/common/utils/Constants.java
> $subject
> * https://github.com/wso2-enterprise/asgardeo-product/issues/19364
=> Introduced retry mechanism for Choreo API endpint request

components/org.wso2.carbon.identity.conditional.auth.functions.utils/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/utils/FilterAuthenticatorsFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/utils/FilterAuthenticatorsFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/utils/internal/UtilsFunctionServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.utils/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/utils/internal/UtilsFunctionServiceHolder.java, pom.xml
Fix related to  https://github.com/wso2-enterprise/asgardeo-product/issues/20580
Related PRs : 
- https://github.com/wso2/identity-apps/pull/4781
=> Add support function to filter authenticators

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallAnalyticsFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.choreo/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.elk/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/elk/CallElasticFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/notification/SendEmailFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.session/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/MicrosoftEmailVerificationFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/model/JsWrapperFactoryProvider.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasRoleFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/IsMemberOfAnyOfGroupsFunctionImplTest.java, pom.xml
> Use createJsGraphBuilderFactoryFromConfig function from FrameworkUtils as using the function from internal package causes class not found exception since internal package is not exported. 
> https://github.com/wso2/product-is/issues/17132
=> Use createJsGraphBuilderFactoryFromConfig function from FrameworkUtils

components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml
This PR adds missing imports that cause runtime exceptions to be thrown in adaptive authentication flows. This was observed when testing issues [1]. The root cause mentioned in [1] is already fixed but the flow is still blocked due to the java.lang.NoClassDefFoundError errors thrown by the missing imports.
[1] https://github.com/wso2/product-is/issues/20010
=> Fix runtime errors in adaptive authentication flows due to missing imports

.github/workflows/pr-builder.yml, components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/resources/testng.xml
- PR builder was failing continuously due to an indentation issue in the workflow yaml file. This PR fixes that issue and set repo to be built on the latest java 11 patch version.
- Intermittent/ frequent build issue was observed in `org.wso2.carbon.identity.conditional.auth.functions.http` component due to a test/ s failures in the http get or post related functions. As per the logs, this is due to `httpGet`/ `httpPost` functions getting undefined while executing the JS graph. 
- The root cause is as follows. Both of these tests extends the `JsSequenceHandlerAbstractTest` class which initializes the `JsSequenceHandlerRunner`. This class initializes the `jsFunctionRegistry`, `graphBuilderFactory`, etc within it's [init method](https://github.com/wso2-extensions/identity-conditional-auth-fu …
=> Fix PR builder and http component test failure

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/AbstractHTTPFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/util/ClientCredentialAuthConfig.java
=> Fixed issue of consider outcome for the callback

components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/UserStoreFunctions.java
- Fix authentication Context being null in authenticated user JS proxy object
=> Fix authentication Context being null in authenticated user JS proxy object

components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/notification/SendEmailFunctionImpl.java
- When `SendMail` method is invoked from an adaptive authentication script, the email is not sent to federated users since federated user claims (which includes user email) are not available when building the email notification. 
- Therefore, with this PR, federated user attributes are appended to event properties inside `SendMail` method.
- https://github.com/wso2-extensions/identity-event-handler-notification/pull/240
- https://github.com/wso2-extensions/identity-local-auth-emailotp/pull/32
=> Add Federated User Attributes to Event Properties in `SendMail` Method

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/util/AuthConfigFactory.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/util/BearerAuthConfig.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/http/http-get-test-auth-config-with-basic.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/http/http-get-test-auth-config-with-bearer.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/http/http-post-test-auth-config-with-basic.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/resources/org/wso2/carbon/identity/conditional/auth/functions/http/http-post-test-auth-config-with-bearer.xml
> $subject
- https://github.com/wso2-enterprise/asgardeo-product/issues/23238
=> Updated the authconfigs model from basicauth to basic and bearertoken to bearer

components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImpl.java
> $subject
- https://github.com/wso2/product-is/issues/20862
=> Fix Unable to use parseInt with setCookie in adaptive script

components/org.wso2.carbon.identity.conditional.auth.functions.common/pom.xml
To resolve the issue of OpenJDK Nashorn scriptObjectMirror class not being found for Open JDK nashorn based script execution engine, we need to add these dynamic imports.
This was working in authentication framework due to the following import
https://github.com/wso2/carbon-identity-framework/blob/ae763b68543c37dce3b861addee3a8dd4aac7603/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/pom.xml#L315
=> Add dynamic import for OpenJDK Nashorn scriptObjectMirror

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/internal/AnalyticsFunctionsServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.analytics/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/analytics/CallAnalyticsFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/internal/ChoreoFunctionServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.elk/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/elk/internal/ElasticFunctionsServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.elk/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/elk/CallElasticFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPGetFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/http/HTTPPostFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.notification/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/notification/SendEmailFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasAnyOfTheRolesFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/HasRoleFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/IsMemberOfAnyOfGroupsFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.utils/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/utils/GetMaskedValueFunctionImplTest.java, components/org.wso2.carbon.identity.conditional.auth.functions.utils/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/utils/ResolveMultiAttributeLoginIdentifierFunctionImplTest.java, pom.xml
$subject
Related to https://github.com/wso2/product-is/issues/19506
=> Use getKeystoreInstance from KeystoreUtils

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/IsMemberOfAnyOfGroupsFunctionImpl.java
Adding support to resolve groups claim uri from an existing session for "isMemberOfAnyOfGroups" adaptive function. 
In an existing session, the authenticator has to be resolved from `PreviousAuthenticatedIdP`. This pr adds this support.
=> Resolve groups claim URI from existing session 

components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/GetCookieFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/SetCookieFunctionImpl.java, pom.xml
=> Sign content and signature validation using new util method

components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/CookieFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/GetCookieFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/SetCookieFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/internal/HTTPFunctionsServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/internal/HTTPFunctionsServiceHolder.java, components/org.wso2.carbon.identity.conditional.auth.functions.http/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/http/util/HTTPConstants.java, pom.xml
$ 
Logic will create context keystore if not exists
Public Issue: https://github.com/wso2/product-is/issues/21985
Todo
=> [Cookie] Introduce of context keystore for GetCookie, SetCookie Fn for signing

components/org.wso2.carbon.identity.conditional.auth.functions.choreo/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/choreo/CallChoreoFunctionImpl.java
> There is possible memory leak due to not closing the http connection after the required response is received.
In httpClient version 5.x the automatic resource deallocation happens but in httpClient version 4.x the deallocation has to be done.
ex: EntityUtils.consume(entityOne);
Ref:- https://www.baeldung.com/apache-httpclient-vs-closeablehttpclient#1-automatic-resource-deallocation-httpclient-4x
```
httpClient.execute(httpGetOne, responseOne -> {
HttpEntity entityOne = responseOne.getEntity();
EntityUtils.consume(entityOne);
assertThat(responseOne.getCode()).isEqualTo(HttpStatus.SC_OK);
return responseOne;
});
```
=> Fix memory leak of the callChoreo access token request helper function

components/org.wso2.carbon.identity.conditional.auth.functions.analytics/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.choreo/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.common/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.elk/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.http/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.jwt.decode/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.notification/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.user.store/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.user/pom.xml, components/org.wso2.carbon.identity.conditional.auth.functions.utils/pom.xml
- We need to bundle graal-sdk as an OSGi bundle and expose only the selected packages.
- So required packages need to be imported.
- This PR adds the required imports
- https://github.com/wso2/product-is/issues/21276
=> Import org.graalvm.polyglot package and sub-packages

components/org.wso2.carbon.identity.conditional.auth.functions.session/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/session/function/ExecuteActionFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.session/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/session/function/GetSessionDataFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.session/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/session/function/GetUserSessionDataFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.session/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/session/function/IsWithinSessionLimitFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.session/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/session/function/IsWithinSessionLimitFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.session/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/session/function/KillSessionFunction.java
- `isWithinSessionLimit`, `killSession` and `getSessionData` functions are currently not packed with Identity Server
- There are maintained and packed functions in Identity Server which offer the same functionality
- So these functions will not be supported with the new GraalJS based adaptive authentication script engine implementation by default and will be deprecated.
- However the support can be provided similar to other functions
=> Deprecate session related functions

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/model/utils/UserPasswordUpdateModel.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/test/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImplTest.java
This pull request enhances the `updateUserPassword` functionality by introducing a new parameter to bypass password validation and updates the corresponding test cases to support this change. It also improves error handling and logging for better maintainability and debugging.
* Added a new `skipPasswordValidation` parameter to allow bypassing password pattern validation. This is implemented by setting a thread-local variable using `UserCoreUtil.setSkipPasswordPatternValidationThreadLocal`.
* Improved argument parsing to handle multiple optional parameters (`eventHandlers` and `skipPasswordValidation`) and updated error messages to reflect the expected argument types.
* Updated the `updateUserPasswordWithEmptyInputDataProvider` test data to include the new `skipPasswordValidation` …
=> Provide capability to skip password pattern validation during on demand password migration

components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImpl.java
This PR updates malformed Java doc comment in the [updateUserPassword](https://github.com/Shenali-SJ/identity-conditional-auth-functions/blob/7793eec178457558fff84ab6512c0c7d40db74ed/components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/UpdateUserPasswordFunctionImpl.java#L63) method.
- https://github.com/wso2/product-is/issues/24228
- https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/208
=> Update malformed Java doc comment tags

components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/GetUsersWithClaimValuesFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/GetUsersWithClaimValuesFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/UserStoreFunctions.java, components/org.wso2.carbon.identity.conditional.auth.functions.user.store/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/store/internal/UserStoreFunctionsServiceComponent.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/RemoveAssociatedLocalUserFunction.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/RemoveAssociatedLocalUserFunctionImpl.java, components/org.wso2.carbon.identity.conditional.auth.functions.user/src/main/java/org/wso2/carbon/identity/conditional/auth/functions/user/internal/UserFunctionsServiceComponent.java
This PR introduces 2 new conditional auth functions. Please find the functions and their purposes below.
1. **getUsersWithClaimValues:** This method returns multiple users with values provided for the claims through adaptive script.
2. **removeAssociatedLocalUser:** This method will remove the local user association from a federated user.
Related issue:
- https://github.com/wso2/product-is/issues/25042
=> Add conditional auth functions to remove local user association and multiple user retrieval
